# Site settings
email: zhendi.huang@hotmail.com
baseurl: ""
paginate: 6
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Zhendi
description:
url: ""
twitter_username:
default_img:

# Profile settings
name: Zhendi Huang
profile_img: /img/pf.jpg
profile: My name is Zhendi. I am a data analyst and a developer. I built up this website to share interesting ideas with you. If you like what I am doing, send me a message.
social:
  github: https://github.com/GrietjeWong

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
